DROP DATABASE IF EXISTS Spotted;
CREATE DATABASE Spotted;
USE Spotted;

CREATE TABLE UTENTI (
    Username VARCHAR(100) PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Cognome VARCHAR(100) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Ruolo ENUM('studente', 'admin') DEFAULT 'studente',
    Stato ENUM('attivo', 'bloccato') DEFAULT 'attivo'
) ENGINE=InnoDB;


CREATE TABLE CATEGORIE (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) UNIQUE NOT NULL
) ENGINE=InnoDB;


CREATE TABLE SOTTOCATEGORIE (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Categoria_id INT NOT NULL,

    UNIQUE (Nome, Categoria_id),
    FOREIGN KEY (Categoria_id) REFERENCES CATEGORIE(Id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE SPOT (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Titolo VARCHAR(255) NOT NULL,
    Testo_spot TEXT NOT NULL,
    Data_Inserimento DATETIME DEFAULT CURRENT_TIMESTAMP,
    Categoria_id INT NOT NULL,
    Sottocategoria_id INT,
    Utente_username VARCHAR(100),
    Admin_approvatore VARCHAR(100) NULL, 
    Data_approvazione DATETIME NULL,

    FOREIGN KEY (Categoria_id) REFERENCES CATEGORIE(Id),
    FOREIGN KEY (Sottocategoria_id) REFERENCES SOTTOCATEGORIE(Id) ON DELETE SET NULL,
    FOREIGN KEY (Utente_username) REFERENCES UTENTI(Username) ON DELETE SET NULL,
    FOREIGN KEY (Admin_approvatore) REFERENCES UTENTI(Username) ON DELETE SET NULL
) ENGINE=InnoDB;


CREATE TABLE PREFERITI (
    Utente_username VARCHAR(100) NOT NULL,
    Spot_id INT NOT NULL,

    PRIMARY KEY (Utente_username, Spot_id),
    FOREIGN KEY (Utente_username) REFERENCES UTENTI(Username) ON DELETE CASCADE,
    FOREIGN KEY (Spot_id) REFERENCES SPOT(Id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE COMMENTI (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Testo TEXT NOT NULL,
    Data DATETIME DEFAULT CURRENT_TIMESTAMP,
    Spot_id INT NOT NULL,
    Utente_username VARCHAR(100) NOT NULL,

    FOREIGN KEY (Spot_id) REFERENCES SPOT(Id) ON DELETE CASCADE,
    FOREIGN KEY (Utente_username) REFERENCES UTENTI(Username) ON DELETE CASCADE
) ENGINE=InnoDB;





