DROP DATABASE IF EXISTS spotted;
CREATE DATABASE spotted;
USE spotted;

CREATE TABLE TIPI_UTENTI (
    idTipo INT AUTO_INCREMENT PRIMARY KEY, 
    nomeTipo VARCHAR(100) NOT NULL
 )ENGINE=InnoDB;

CREATE TABLE UTENTI (
    username VARCHAR(100) PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cognome VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    stato ENUM('attivo', 'bloccato') DEFAULT 'attivo',
    idTipo INT NOT NULL, 

    FOREIGN KEY (idTipo) REFERENCES TIPI_UTENTI(idTipo) ON DELETE CASCADE
) ENGINE=InnoDB;



CREATE TABLE CATEGORIE (
    idCategoria INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) UNIQUE NOT NULL
) ENGINE=InnoDB;


CREATE TABLE SOTTOCATEGORIE (
    idSottoCategoria INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    idCategoria INT NOT NULL,

    UNIQUE (nome, idCategoria),
    FOREIGN KEY (idCategoria) REFERENCES CATEGORIE(idCategoria) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE SPOT (
    idSpot INT AUTO_INCREMENT PRIMARY KEY,
    titolo VARCHAR(255) NOT NULL,
    testo TEXT NOT NULL,
    dataInserimento DATETIME DEFAULT CURRENT_TIMESTAMP,
    stato ENUM('in_attesa', 'approvato', 'rifiutato') DEFAULT 'in_attesa',
    idCategoria INT NOT NULL,
    idSottoCategoria INT,
    usernameUtente VARCHAR(100),
    usernameAdminApprovato VARCHAR(100) NULL, 
    dataApprovazione DATETIME NULL,

    FOREIGN KEY (idCategoria) REFERENCES CATEGORIE(idCategoria),
    FOREIGN KEY (idSottoCategoria) REFERENCES SOTTOCATEGORIE(idSottoCategoria) ON DELETE SET NULL,
    FOREIGN KEY (usernameUtente) REFERENCES UTENTI(username) ON DELETE SET NULL,
    FOREIGN KEY (usernameAdminApprovato) REFERENCES UTENTI(username) ON DELETE SET NULL
) ENGINE=InnoDB;


CREATE TABLE PREFERITI (
    usernameUtente VARCHAR(100) NOT NULL,
    idSpot INT NOT NULL,

    PRIMARY KEY (usernameUtente, idSpot),
    FOREIGN KEY (usernameUtente) REFERENCES UTENTI(username) ON DELETE CASCADE,
    FOREIGN KEY (idSpot) REFERENCES SPOT(idSpot) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE COMMENTI (
    idCommento INT AUTO_INCREMENT PRIMARY KEY,
    testo TEXT NOT NULL,
    dataPubblicazione DATETIME DEFAULT CURRENT_TIMESTAMP,
    idSpot INT NOT NULL,
    usernameUtente VARCHAR(100) NOT NULL,
    idCommentoRisposto INT DEFAULT NULL,

    FOREIGN KEY (idSpot) REFERENCES SPOT(idSpot) ON DELETE CASCADE,
    FOREIGN KEY (usernameUtente) REFERENCES UTENTI(username) ON DELETE CASCADE,
    FOREIGN KEY (idCommentoRisposto) REFERENCES COMMENTI(idCommento) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE NOTIFICHE (
    idNotifica INT AUTO_INCREMENT PRIMARY KEY,
    usernameDestinatario VARCHAR(100) NOT NULL,
    testo VARCHAR(255) NOT NULL,
    link VARCHAR(255),
    letta BOOLEAN DEFAULT FALSE,
    dataNotifica DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usernameDestinatario) REFERENCES UTENTI(username) ON DELETE CASCADE
) ENGINE=InnoDB;





